const image = '../assets/images/image1.png'

const exams = [
    {
        "id": "1",
        "exam_code": "402",
        "exam_name": "System Audit",
        "exam_date": "2023-10-31",
        "exam_time": "12:00:00",
        "exam_duration": 2,
        "exam_status": false,
        "exam_created": "2023-10-30T00:17:50.154681Z",
        "exam_updated": "2023-10-30T00:17:50.154774Z",
        "qr_code": "https://imgs.search.brave.com/7__XsFkjrTNSGDwuQ6w-FyhwAkMFqeP1Z8RPXAUSYSg/rs:fit:560:320:1/g:ce/aHR0cHM6Ly91cGxv/YWQud2lraW1lZGlh/Lm9yZy93aWtpcGVk/aWEvY29tbW9ucy90/aHVtYi9kL2QwL1FS/X2NvZGVfZm9yX21v/YmlsZV9FbmdsaXNo/X1dpa2lwZWRpYS5z/dmcvNjQwcHgtUVJf/Y29kZV9mb3JfbW9i/aWxlX0VuZ2xpc2hf/V2lraXBlZGlhLnN2/Zy5wbmc",
        "exam_creator": "Mr. Rapahel",
        "department": "Computing and Information Technology",
        "school": "School of Engineering and Technology",
        "students":[
            {
                "id": "1",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:00:00",
            },
            {
                "id": "2",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:00:00",
            },
            {
                "id": "3",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:04:00",
            },
            {
                "id": "4",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:05:00",
            },
            {
                "id": "5",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:06:00",
            },
            {
                "id": "6",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:07:00",
            },
            {
                "id": "7",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:08:00",
            },
            {
                "id": "8",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:15:00",
            },
            {
                "id": "9",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:16:00",
            },
            {
                "id": "10",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:17:00",
            }
        ]
    },
    {
        "id": "2",
        "exam_code": "401",
        "exam_name": "system security",
        "exam_date": "2023-10-31",
        "exam_time": "12:00:00",
        "exam_duration": 1,
        "exam_status": false,
        "exam_created": "2023-10-30T00:24:54.917186Z",
        "exam_updated": "2023-10-30T00:24:54.917240Z",
        "qr_code": "https://imgs.search.brave.com/7__XsFkjrTNSGDwuQ6w-FyhwAkMFqeP1Z8RPXAUSYSg/rs:fit:560:320:1/g:ce/aHR0cHM6Ly91cGxv/YWQud2lraW1lZGlh/Lm9yZy93aWtpcGVk/aWEvY29tbW9ucy90/aHVtYi9kL2QwL1FS/X2NvZGVfZm9yX21v/YmlsZV9FbmdsaXNo/X1dpa2lwZWRpYS5z/dmcvNjQwcHgtUVJf/Y29kZV9mb3JfbW9i/aWxlX0VuZ2xpc2hf/V2lraXBlZGlhLnN2/Zy5wbmc",
        "exam_creator": "Mr. Rapahel",
        "department": "Computing and Information Technology",
        "school": "School of Engineering and Technology",
        "students":[
            {
                "id": "1",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:00:00",
            },
            {
                "id": "2",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:00:00",
            },
            {
                "id": "3",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:04:00",
            },
            {
                "id": "4",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:05:00",
            },
            {
                "id": "5",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:06:00",
            },
            {
                "id": "6",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:07:00",
            },
            {
                "id": "7",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:08:00",
            },
            {
                "id": "8",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:15:00",
            },
            {
                "id": "9",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:16:00",
            },
            {
                "id": "10",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:17:00",
            }
        ]
    },
    {
        "id": "3",
        "exam_code": "419",
        "exam_name": "Enterprise Resource Planning",
        "exam_date": "2023-11-25",
        "exam_time": "12:00:00",
        "exam_duration": 3,
        "exam_status": false,
        "exam_created": "2023-11-07T17:49:08.934472Z",
        "exam_updated": "2023-11-07T17:49:08.934493Z",
        "qr_code": "https://imgs.search.brave.com/7__XsFkjrTNSGDwuQ6w-FyhwAkMFqeP1Z8RPXAUSYSg/rs:fit:560:320:1/g:ce/aHR0cHM6Ly91cGxv/YWQud2lraW1lZGlh/Lm9yZy93aWtpcGVk/aWEvY29tbW9ucy90/aHVtYi9kL2QwL1FS/X2NvZGVfZm9yX21v/YmlsZV9FbmdsaXNo/X1dpa2lwZWRpYS5z/dmcvNjQwcHgtUVJf/Y29kZV9mb3JfbW9i/aWxlX0VuZ2xpc2hf/V2lraXBlZGlhLnN2/Zy5wbmc",
        "exam_creator": "Mr. Rapahel",
        "department": "Computing and Information Technology",
        "school": "School of Engineering and Technology",
        "students":[
            {
                "id": "1",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:00:00",
            },
            {
                "id": "2",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:00:00",
            },
            {
                "id": "3",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:04:00",
            },
            {
                "id": "4",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:05:00",
            },
            {
                "id": "5",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:06:00",
            },
            {
                "id": "6",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:07:00",
            },
            {
                "id": "7",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:08:00",
            },
            {
                "id": "8",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:15:00",
            },
            {
                "id": "9",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:16:00",
            },
            {
                "id": "10",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:17:00",
            }
        ]
    },
    {
        "id": "4",
        "exam_code": "419",
        "exam_name": "Enterprise Resource Planning",
        "exam_date": "2023-11-25",
        "exam_time": "12:00:00",
        "exam_duration": 3,
        "exam_status": false,
        "exam_created": "2023-11-07T17:49:08.934472Z",
        "exam_updated": "2023-11-07T17:49:08.934493Z",
        "qr_code": "https://imgs.search.brave.com/7__XsFkjrTNSGDwuQ6w-FyhwAkMFqeP1Z8RPXAUSYSg/rs:fit:560:320:1/g:ce/aHR0cHM6Ly91cGxv/YWQud2lraW1lZGlh/Lm9yZy93aWtpcGVk/aWEvY29tbW9ucy90/aHVtYi9kL2QwL1FS/X2NvZGVfZm9yX21v/YmlsZV9FbmdsaXNo/X1dpa2lwZWRpYS5z/dmcvNjQwcHgtUVJf/Y29kZV9mb3JfbW9i/aWxlX0VuZ2xpc2hf/V2lraXBlZGlhLnN2/Zy5wbmc",
        "exam_creator": "Mr. Rapahel",
        "department": "Computing and Information Technology",
        "school": "School of Engineering and Technology",
        "students":[
            {
                "id": "1",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:00:00",
            },
            {
                "id": "2",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:00:00",
            },
            {
                "id": "3",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:04:00",
            },
            {
                "id": "4",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:05:00",
            },
            {
                "id": "5",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:06:00",
            },
            {
                "id": "6",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:07:00",
            },
            {
                "id": "7",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:08:00",
            },
            {
                "id": "8",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:15:00",
            },
            {
                "id": "9",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:16:00",
            },
            {
                "id": "10",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:17:00",
            }
        ]
    },
    {
        "id": "5",
        "exam_code": "419",
        "exam_name": "Enterprise Resource Planning",
        "exam_date": "2023-11-25",
        "exam_time": "12:00:00",
        "exam_duration": 3,
        "exam_status": false,
        "exam_created": "2023-11-07T17:49:08.934472Z",
        "exam_updated": "2023-11-07T17:49:08.934493Z",
        "qr_code": "https://imgs.search.brave.com/7__XsFkjrTNSGDwuQ6w-FyhwAkMFqeP1Z8RPXAUSYSg/rs:fit:560:320:1/g:ce/aHR0cHM6Ly91cGxv/YWQud2lraW1lZGlh/Lm9yZy93aWtpcGVk/aWEvY29tbW9ucy90/aHVtYi9kL2QwL1FS/X2NvZGVfZm9yX21v/YmlsZV9FbmdsaXNo/X1dpa2lwZWRpYS5z/dmcvNjQwcHgtUVJf/Y29kZV9mb3JfbW9i/aWxlX0VuZ2xpc2hf/V2lraXBlZGlhLnN2/Zy5wbmc",
        "exam_creator": "Mr. Rapahel",
        "department": "Computing and Information Technology",
        "school": "School of Engineering and Technology",
        "students":[
            {
                "id": "1",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:00:00",
            },
            {
                "id": "2",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:00:00",
            },
            {
                "id": "3",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:04:00",
            },
            {
                "id": "4",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:05:00",
            },
            {
                "id": "5",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:06:00",
            },
            {
                "id": "6",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:07:00",
            },
            {
                "id": "7",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:08:00",
            },
            {
                "id": "8",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:15:00",
            },
            {
                "id": "9",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:16:00",
            },
            {
                "id": "10",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:17:00",
            }
        ]
    },
    {
        "id": "6",
        "exam_code": "419",
        "exam_name": "Enterprise Resource Planning",
        "exam_date": "2023-11-25",
        "exam_time": "12:00:00",
        "exam_duration": 3,
        "exam_status": false,
        "exam_created": "2023-11-07T17:49:08.934472Z",
        "exam_updated": "2023-11-07T17:49:08.934493Z",
        "qr_code": "https://imgs.search.brave.com/7__XsFkjrTNSGDwuQ6w-FyhwAkMFqeP1Z8RPXAUSYSg/rs:fit:560:320:1/g:ce/aHR0cHM6Ly91cGxv/YWQud2lraW1lZGlh/Lm9yZy93aWtpcGVk/aWEvY29tbW9ucy90/aHVtYi9kL2QwL1FS/X2NvZGVfZm9yX21v/YmlsZV9FbmdsaXNo/X1dpa2lwZWRpYS5z/dmcvNjQwcHgtUVJf/Y29kZV9mb3JfbW9i/aWxlX0VuZ2xpc2hf/V2lraXBlZGlhLnN2/Zy5wbmc",
        "exam_creator": "Mr. Rapahel",
        "department": "Computing and Information Technology",
        "school": "School of Engineering and Technology",
        "students":[
            {
                "id": "1",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:00:00",
            },
            {
                "id": "2",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:00:00",
            },
            {
                "id": "3",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:04:00",
            },
            {
                "id": "4",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:05:00",
            },
            {
                "id": "5",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:06:00",
            },
            {
                "id": "6",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:07:00",
            },
            {
                "id": "7",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:08:00",
            },
            {
                "id": "8",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:15:00",
            },
            {
                "id": "9",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:16:00",
            },
            {
                "id": "10",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:17:00",
            }
        ]
    },
    {
        "id": "7",
        "exam_code": "419",
        "exam_name": "Enterprise Resource Planning",
        "exam_date": "2023-11-25",
        "exam_time": "12:00:00",
        "exam_duration": 3,
        "exam_status": false,
        "exam_created": "2023-11-07T17:49:08.934472Z",
        "exam_updated": "2023-11-07T17:49:08.934493Z",
        "qr_code": "https://imgs.search.brave.com/7__XsFkjrTNSGDwuQ6w-FyhwAkMFqeP1Z8RPXAUSYSg/rs:fit:560:320:1/g:ce/aHR0cHM6Ly91cGxv/YWQud2lraW1lZGlh/Lm9yZy93aWtpcGVk/aWEvY29tbW9ucy90/aHVtYi9kL2QwL1FS/X2NvZGVfZm9yX21v/YmlsZV9FbmdsaXNo/X1dpa2lwZWRpYS5z/dmcvNjQwcHgtUVJf/Y29kZV9mb3JfbW9i/aWxlX0VuZ2xpc2hf/V2lraXBlZGlhLnN2/Zy5wbmc",
        "exam_creator": "Mr. Rapahel",
        "department": "Computing and Information Technology",
        "school": "School of Engineering and Technology",
        "students":[
            {
                "id": "1",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:00:00",
            },
            {
                "id": "2",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:00:00",
            },
            {
                "id": "3",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:04:00",
            },
            {
                "id": "4",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:05:00",
            },
            {
                "id": "5",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:06:00",
            },
            {
                "id": "6",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:07:00",
            },
            {
                "id": "7",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:08:00",
            },
            {
                "id": "8",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:15:00",
            },
            {
                "id": "9",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:16:00",
            },
            {
                "id": "10",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:17:00",
            }
        ]
    },
    {
        "id": "8",
        "exam_code": "419",
        "exam_name": "Enterprise Resource Planning",
        "exam_date": "2023-11-25",
        "exam_time": "12:00:00",
        "exam_duration": 3,
        "exam_status": false,
        "exam_created": "2023-11-07T17:49:08.934472Z",
        "exam_updated": "2023-11-07T17:49:08.934493Z",
        "qr_code": "https://imgs.search.brave.com/7__XsFkjrTNSGDwuQ6w-FyhwAkMFqeP1Z8RPXAUSYSg/rs:fit:560:320:1/g:ce/aHR0cHM6Ly91cGxv/YWQud2lraW1lZGlh/Lm9yZy93aWtpcGVk/aWEvY29tbW9ucy90/aHVtYi9kL2QwL1FS/X2NvZGVfZm9yX21v/YmlsZV9FbmdsaXNo/X1dpa2lwZWRpYS5z/dmcvNjQwcHgtUVJf/Y29kZV9mb3JfbW9i/aWxlX0VuZ2xpc2hf/V2lraXBlZGlhLnN2/Zy5wbmc",
        "exam_creator": "Mr. Rapahel",
        "department": "Computing and Information Technology",
        "school": "School of Engineering and Technology",
        "students":[
            {
                "id": "1",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:00:00",
            },
            {
                "id": "2",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:00:00",
            },
            {
                "id": "3",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:04:00",
            },
            {
                "id": "4",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:05:00",
            },
            {
                "id": "5",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:06:00",
            },
            {
                "id": "6",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:07:00",
            },
            {
                "id": "7",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:08:00",
            },
            {
                "id": "8",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:15:00",
            },
            {
                "id": "9",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:16:00",
            },
            {
                "id": "10",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:17:00",
            }
        ]
    },
    {
        "id": "9",
        "exam_code": "419",
        "exam_name": "Enterprise Resource Planning",
        "exam_date": "2023-11-25",
        "exam_time": "12:00:00",
        "exam_duration": 3,
        "exam_status": false,
        "exam_created": "2023-11-07T17:49:08.934472Z",
        "exam_updated": "2023-11-07T17:49:08.934493Z",
        "qr_code": "https://imgs.search.brave.com/7__XsFkjrTNSGDwuQ6w-FyhwAkMFqeP1Z8RPXAUSYSg/rs:fit:560:320:1/g:ce/aHR0cHM6Ly91cGxv/YWQud2lraW1lZGlh/Lm9yZy93aWtpcGVk/aWEvY29tbW9ucy90/aHVtYi9kL2QwL1FS/X2NvZGVfZm9yX21v/YmlsZV9FbmdsaXNo/X1dpa2lwZWRpYS5z/dmcvNjQwcHgtUVJf/Y29kZV9mb3JfbW9i/aWxlX0VuZ2xpc2hf/V2lraXBlZGlhLnN2/Zy5wbmc",
        "exam_creator": "Mr. Rapahel",
        "department": "Computing and Information Technology",
        "school": "School of Engineering and Technology",
        "students":[
            {
                "id": "1",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:00:00",
            },
            {
                "id": "2",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:00:00",
            },
            {
                "id": "3",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:04:00",
            },
            {
                "id": "4",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:05:00",
            },
            {
                "id": "5",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:06:00",
            },
            {
                "id": "6",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:07:00",
            },
            {
                "id": "7",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:08:00",
            },
            {
                "id": "8",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:15:00",
            },
            {
                "id": "9",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:16:00",
            },
            {
                "id": "10",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:17:00",
            }
        ]
    },
    {
        "id": "10",
        "exam_code": "419",
        "exam_name": "Enterprise Resource Planning",
        "exam_date": "2023-11-25",
        "exam_time": "12:00:00",
        "exam_duration": 3,
        "exam_status": false,
        "exam_created": "2023-11-07T17:49:08.934472Z",
        "exam_updated": "2023-11-07T17:49:08.934493Z",
        "qr_code": "https://imgs.search.brave.com/7__XsFkjrTNSGDwuQ6w-FyhwAkMFqeP1Z8RPXAUSYSg/rs:fit:560:320:1/g:ce/aHR0cHM6Ly91cGxv/YWQud2lraW1lZGlh/Lm9yZy93aWtpcGVk/aWEvY29tbW9ucy90/aHVtYi9kL2QwL1FS/X2NvZGVfZm9yX21v/YmlsZV9FbmdsaXNo/X1dpa2lwZWRpYS5z/dmcvNjQwcHgtUVJf/Y29kZV9mb3JfbW9i/aWxlX0VuZ2xpc2hf/V2lraXBlZGlhLnN2/Zy5wbmc",
        "exam_creator": "Mr. Rapahel",
        "department": "Computing and Information Technology",
        "school": "School of Engineering and Technology",
        "students":[
            {
                "id": "1",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:00:00",
            },
            {
                "id": "2",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:00:00",
            },
            {
                "id": "3",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:04:00",
            },
            {
                "id": "4",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:05:00",
            },
            {
                "id": "5",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:06:00",
            },
            {
                "id": "6",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:07:00",
            },
            {
                "id": "7",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:08:00",
            },
            {
                "id": "8",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:15:00",
            },
            {
                "id": "9",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:16:00",
            },
            {
                "id": "10",
                "student_id": "123456",
                "student_name": "John Doe",
                "attendance_time": "12:17:00",
            }
        ]
    }

]

export default exams;